### ISSUE TITLE
Impossible to dynamically set urls

### ISSUE THREAD

**Issue by mikesol** [unmock/unmock-js#148]
There are many cases in which we may want to set a URL dynamically, ie via an ENV variable. For example, see how the OriginProtocol interacts with Facebook: https://github.com/OriginProtocol/origin/blob/b7aea6f263ca4e5b4ebc713471d58a3844e55481/infra/bridge/test/facebook.js . The Facebook API endpoint is set in an env variable.

**Comment by idantene** [comment]
Do we *want* to support this behavior though? What use case does it serve?

**Comment by idantene** [comment]
Now implemented (in #207, #212, #219 )
