### ISSUE TITLE
Merge unmock-core to unmock-node

### ISSUE THREAD

**Issue by ksaaskil** [unmock/unmock-js#150]
`unmock-core` was originally an isomorphic package usable both in Node.js and browser. The browser implementation is not needed anymore, so `unmock-core` can be merged to `unmock-node` inside, for example, `core` directory.

Also delete `unmock-jsdom`.

**Comment by idantene** [comment]
Done in #182 (albeit merged `unmock-node` into `unmock-core` instead of the other way around).
