### ISSUE TITLE
Body in UnmockResponse is string when should be JSON

### ISSUE THREAD

**Issue by ksaaskil** [unmock/unmock-js#183]
It's unexpected that `body` in `UnmockResponse` (alias for `ISerializedResponse`) is represented as `string` even when the response is `application/json`. Change it to work as `UnmockRequest` so that the body is `string | object | undefined`.

**Comment by idantene** [comment]
`s/UnmockResponse/ISerializedResponse/g`

Where does this happen? Here it's clearly being stringified... https://github.com/unmock/unmock-js/blob/73cc0003623a9bb6162e1e313c1dff72b7c0d734/packages/unmock-core/src/generator.ts#L305

**Comment by ksaaskil** [comment]
So this would mean
- Changing the body type to `string | object`
- Removing the cast to string in the mock generator
- Casting to string when sending the response from Node.js interceptor.

As reference, also `yesno` [represents the response](https://github.com/FormidableLabs/yesno/blob/master/src/http-serializer.ts#L37) as string or object.

**Comment by ksaaskil** [comment]
After this is done, one can remove the `JSON.parse` from [this example](https://github.com/unmock/unmock-examples/blob/a3a2e1df905610181e4e8691ba2ecdb4db19d4b6/hello-world-javascript/hello.test.js#L50).

**Comment by ksaaskil** [comment]
We'll keep the body as `string` for now to avoid typing it as `any` (typing as union type is very cumbersome for testing).
