### ISSUE TITLE
Allow the path specification with an array

### ISSUE THREAD

**Issue by mikesol** [unmock/unmock-js#252]
As per https://github.com/unmock/unmock-js/tree/new-readme#specifying-path.
Also, the more I think about it, the more the regex in the array should be a key-value pair so that the `responseBody` override should be able to reference it. So...

```typescript
["id",["foo", /[123]+/],"bar"]
```

Instead of 

```typescript
["id", /[123]+/, "bar"]
```

The former allows for `responseBody({ path: "/id/{foo}"})` whereas the latter does not. Of course, we should support the latter as well, in which case we just generate a random name for the path parameter (ie a uuid).

**Comment by idantene** [comment]
That's also directly related to our discussion of supporting regex/specific endpoints that are defined by a path parameter.
I'd imagine `responseBody({ path: "/id/*" })` to have the same effect as listed above (with a named path parameter), as well as `responseBody({ path: "/id/3" })` to have effect on that specific endpoint.
