### ISSUE TITLE
Learnings from School of Startups workshop

### ISSUE THREAD

**Issue by ksaaskil** [unmock/unmock-js#301]
### Setting state multiple times can be a gotcha

Re-defining the state overwrites the previous state, so this does not work as expected:
```
githubv3.state(
  transform.withCodes(200),
);
githubv3.state(
  transform.responseBody({ lens: [Arr, 'private'] }).const(true),
);
```

Not sure if that's deliberate or not, anyway it might need some more clarification.

### Usage in JavaScript can be awkward

This pattern loses type information:

```js
describe("my test", () => {
  let github;
  beforeAll(() => {
    github = unmock.on().services.githubv3;
  });
```
With this pattern, variable `github` is typed as `any` in VS Code so the editor has no clue which methods are available. In TypeScript, this can be circumvented by typing the declaration as `let github: IService`.

### Lot of boilerplate required

This is what my tests ended up like:

```js
let githubv3;

describe('Fetching GitHub repositories', () => {
  beforeAll(() => {
    unmock.on();
    githubv3 = unmock.services.githubv3;
  });

  afterAll(() => {
    unmock.off();
  });

  beforeEach(() => {
    githubv3.state(transform.withCodes(200));
  });

  afterEach(() => {
    unmock.reset();
  });

  it('should return an array of repositories', async () => {
    const repos = await fetchGitHubRepos();
    expect(Array.isArray(repos)).toBe(true);
  });
});
```
Then I ended up copying the same boilerplate in another test suite. It could be reduced a bit by the following pattern:
```js
let githubv3;

describe('Fetching GitHub repositories', () => {
  beforeAll(() => {
    unmock.on();
    githubv3 = unmock.services.githubv3;
  });

  afterAll(() => {
    unmock.off();
  });

  beforeEach(() => {
    unmock.reset();
  });

  it('should return an array of repositories', async () => {
    githubv3.state(transform.withCodes(200));
    const repos = await fetchGitHubRepos();
    expect(Array.isArray(repos)).toBe(true);
  });
});
```

In Jest, one could reduce boilerplate a bit by letting users set `testEnvironment: "unmock-jest"` or use a Jest preset (maybe not most handy as one can only define one).

### Adding services can be (too) magical

Adding a service with `yarn add -D @unmock/githubv3` is nice but is a bit too much magic. Maybe something like this would be more explicit:

```js
import github from "@mocks/githubv3";  // Also a different name than @unmock?

unmock.register(github);

// No need for `let github;` declaration, `github` properly typed 
```

### Add `verbose` option

Adding `verbose: true` might make it easier to show what unmock is doing behind the scenes. Alternatively, one should always install also the test reporter if that's not too much.

**Comment by mikesol** [comment]
@ksaaskil 

## Multiple state set
This does not work.
```js
githubv3.state(
  transform.withCodes(200),
);
githubv3.state(
  transform.responseBody({ lens: [Arr, 'private'] }).const(true),
);
```
You'd need to do:
```js
githubv3.state(
  transform.withCodes(200),
  transform.responseBody({ lens: [Arr, 'private'] }).const(true),
);
```
That is (for now) intentional although there is most certainly a better way to document it, and probably a better way to implement it too.

## Usage in JavaScript can be awkward

One way to get around it is to change the API.
```js
  let github;
  beforeAll(() => {
    github = unmock.on().services.githubv3;
  });
```
Can become
```js
beforeAll(() => {
  github = unmock.on().services('githubv3');
});
```
That way we can have a return signature for services.

## Lots of boilerplate required

I noticed this too - it is unfun. I can't think of a good way to 10x fix this problem, just small "perfume on the skunk" fixes, but it is still a skunk. Hm...

## Adding services can be (too) magical

Not against this, but why is it too magical? I'm usually wary of adding an extra step unless it provides some benefit.

## Add `verbose` option

Agreed, and ideally, we can have a `create-react-app` like tool that adds stuff like the reporter, generates unmock boilerplate, etc.

**Comment by ksaaskil** [comment]
> ## Usage in JavaScript can be awkward
> One way to get around it is to change the API.
> 
> ```js
>   let github;
>   beforeAll(() => {
>     github = unmock.on().services.githubv3;
>   });
> ```
> 
> Can become
> 
> ```js
> beforeAll(() => {
>   github = unmock.on().services('githubv3');
> });
> ```
> 
> That way we can have a return signature for services.

I don't think that fixes the problem, the problem is that one still needs to declare `let github`  somwhere that in JS basically says "I have no idea what the type here will be".

> ## Adding services can be (too) magical
> Not against this, but why is it too magical? I'm usually wary of adding an extra step unless it provides some benefit.

It might clarify what's going on if there was an import step, and reduce coupling between tests (so that github service is not accidentally included in all tests not even intending to use `github`). But it can stay as is, just saying the one-time `yarn add -D @unmock/githubv3` does not leave any tracks behind for other poor developers to follow.
